services:
  dev-web-app1:
    container_name: ${HOST_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-php:11
    restart: always
    environment:
      - LETSENCRYPT_HOST=${HOST_NAME}
      - VIRTUAL_HOST=${HOST_NAME}
      - VIRTUAL_PORT=80
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
    volumes:
      - ./src:/home/www
    networks:
      - backend
      - reverse-proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  reverse-proxy:
    external: true
  backend:
    external: true
